import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import type { AddressInfo } from "node:net";
import { loadDataset } from "../adapters/local_data.ts";
import { createAppServer } from "../server.ts";

test("S-14: dashboard service composes real calculations and separate synthetic evidence experiment", async t => {
  const server = createAppServer(await loadDataset());
  server.listen(0, "127.0.0.1");
  await once(server, "listening");
  t.after(() => { server.closeAllConnections(); server.close(); });
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const page = await fetch(base);
  assert.equal(page.status, 200);
  assert.match(await page.text(), /id="event-log"/);
  for (const asset of ["/demo.js", "/replay-explainer.js", "/src/linear_sensitivities.js"]) {
    const response = await fetch(`${base}${asset}`);
    assert.equal(response.status, 200);
    assert.match(response.headers.get("content-type")!, /javascript/);
  }
  const definition = await fetch(`${base}/definition/rules`);
  assert.equal(definition.status, 200);
  assert.match(definition.headers.get("content-type")!, /text\/html/);
  const document = await definition.text();
  assert.match(document, /<h1[^>]*>Calculus rules and experimental bindings<\/h1>/);
  assert.match(document, /<table>[\s\S]*TC-SENS-01[\s\S]*<\/table>/);
  assert.match(document, /href="\/definition\/historical-replay#risk-drives-exposure"/);
  const linkedDocument = await fetch(`${base}/definition/historical-replay`);
  assert.equal(linkedDocument.status, 200);
  const linkedHtml = await linkedDocument.text();
  assert.match(linkedHtml, /id="risk-drives-exposure"/);
  assert.match(linkedHtml, /href="\/definition\/data-provenance"/);
  assert.match(linkedHtml, /<pre><code/);
  const source = await fetch(`${base}/definition/rules?raw=1`);
  assert.match(source.headers.get("content-type")!, /text\/plain/);
  assert.match(await source.text(), /^# Calculus rules and experimental bindings/);
  assert.equal((await fetch(`${base}/document.css`)).status, 200);
  assert.equal((await fetch(`${base}/definition/unknown`)).status, 404);
  assert.equal((await fetch(`${base}/definition/%2e%2e%2fAGENTS.md`)).status, 404);
  const rates = await (await fetch(`${base}/api/rates?date=2024-01-07`)).json();
  assert.ok(rates.observation.date <= "2024-01-07");
  assert.equal(rates.curves.length, 9);
  const baseline = await (await fetch(`${base}/api/replay?strategy=no-trade`)).json();
  assert.equal(baseline.summary.netPnlUsd, 0);
  assert.equal(baseline.comparisons[0].trajectory[0].cumulativePnlUsd, 0);
  assert.equal(baseline.comparisons[0].summary, undefined);
  const controlled = await (await fetch(`${base}/api/replay?strategy=buy-hold&stressBudget=1000`)).json();
  assert.equal(controlled.config.riskPolicy.maxStressLossUsd, 1000);
  const firstEntry = controlled.rows.find((row: { brentPosition: number }) => row.brentPosition > 0);
  assert.ok(firstEntry.brentPosition < 100);
  assert.equal(firstEntry.riskDecision.outcome, "resize");
  assert.ok(firstEntry.riskDecision.evidenceThrough < firstEntry.date);
  assert.equal(controlled.uncontrolled.rows[1].brentPosition, 1000);
  assert.equal(controlled.rows[1].brentPosition, 0);
  assert.equal(controlled.rows.at(-1).riskDecision.outcome, "horizon-close");
  const observed = await (await fetch(`${base}/api/replay?strategy=buy-hold&riskMode=observe&start=2024-01-02&end=2024-02-01`)).json();
  assert.equal(observed.rows[1].brentPosition, 1000);
  assert.equal((await fetch(`${base}/api/replay?riskMode=invalid`)).status, 400);
  assert.equal((await fetch(`${base}/api/replay?tailBudget=-1`)).status, 400);
  const adaptive = await (await fetch(`${base}/api/replay?hedgeMode=adaptive&primaryFloor=1&start=2023-01-03&end=2023-05-01`)).json();
  const planRow = adaptive.rows.find((row: { strategyModel: { plan: unknown } }) => row.strategyModel.plan);
  assert.ok(planRow.strategyModel.plan.steps[0].gainVector.length > 0);
  assert.equal(planRow.strategyModel.plan.reference.minimumExpectedNetPnlUsd, 0);
  assert.equal(planRow.strategyModel.selectedForecast.evidenceThrough, planRow.riskDecision.evidenceThrough);
  assert.ok(planRow.strategyModel.selectedState);
  assert.equal(adaptive.unhedged.config.hedging.mode, "off");
  assert.equal((await fetch(`${base}/api/replay?hedgeMode=invalid`)).status, 400);
  assert.equal((await fetch(`${base}/api/replay?hedgeDepth=7`)).status, 400);
  const unknown = await (await fetch(`${base}/api/analysis?reconciled=false`)).json();
  const resolved = await (await fetch(`${base}/api/analysis?reconciled=true`)).json();
  assert.equal(unknown.decision.action, "seek-evidence");
  assert.equal(resolved.candidates[1].worstRepresentedLossUsd, 130000);
  assert.equal((await fetch(`${base}/api/replay?strategy=unknown`)).status, 400);
  assert.equal((await fetch(`${base}/api/replay?start=2025-01-01&end=2023-01-01`)).status, 400);
  assert.equal((await fetch(`${base}/api/health`, { method: "POST" })).status, 405);
  assert.equal((await fetch(`${base}/missing`)).status, 404);
});
